export const destinations = [
  {
    id: "bukit-panorama-lestari",
    name: "Bukit Panorama Lestari",
    type: "Wisata Alam",
    subtitle: "Sunrise & Trekking",
    description:
      "Bukit dengan jalur trekking ringan \u00b130 menit, menawarkan pemandangan matahari terbit dan hamparan sawah organik.",
    ecoValue: "Jalur trekking berbahan alami, tanpa kendaraan bermotor.",
    activities: [
      "Sunrise trekking",
      "Fotografi alam",
      "Edukasi konservasi lereng",
    ],
    image: "/images/bukit-panorama.jpg",
    eco: true,
  },
  {
    id: "air-terjun-tirta-manud",
    name: "Air Terjun Tirta Manud",
    type: "Wisata Alam",
    subtitle: "Hidden Waterfall",
    description:
      "Air terjun alami dengan kolam dangkal dan sistem pembatasan pengunjung per hari.",
    ecoValue: "Sistem kuota kunjungan untuk mencegah overcapacity.",
    activities: ["Trekking hutan ringan", "Berenang", "Edukasi ekosistem air"],
    image: "/images/air-terjun.jpg",
    eco: true,
  },
  {
    id: "kampung-sawah-organik",
    name: "Kampung Sawah Organik Mandiri",
    type: "Agro-Tourism",
    subtitle: "Pertanian Organik",
    description: "Area persawahan organik yang dikelola warga desa.",
    ecoValue: "Tanpa pestisida kimia, sistem irigasi ramah lingkungan.",
    activities: [
      "Belajar menanam padi",
      "Membajak sawah tradisional",
      "Panen sayur organik",
    ],
    image: "/images/sawah-organik.jpg",
    eco: true,
  },
  {
    id: "kedai-kopi-lembah-hijau",
    name: "Kedai Kopi Lembah Hijau",
    type: "UMKM & Kuliner",
    subtitle: "Farm-to-Cup Coffee",
    description: "Kedai kopi lokal dengan konsep farm-to-cup.",
    ecoValue: "Menggunakan kopi hasil kebun lokal & sedotan bambu.",
    activities: ["Coffee tasting", "Workshop roasting sederhana"],
    image: "/images/kedai-kopi.jpg",
    eco: true,
  },
  {
    id: "sungai-lestari-manud",
    name: "Sungai Lestari Manud",
    type: "Soft Adventure",
    subtitle: "River Activities",
    description: "Sungai untuk arum jeram, tubing ringan & river walk.",
    ecoValue: "Pembatasan plastik & pengawasan sampah.",
    activities: [
      "Arum jeram",
      "River tubing ringan",
      "Edukasi kebersihan sungai",
    ],
    image: "/images/sungai-lestari.jpg",
    eco: true,
  },
  {
    id: "hutan-konservasi-manud",
    name: "Hutan Konservasi Manud Hijau",
    type: "Eco-Tourism & Edukasi",
    subtitle: "Konservasi Alam",
    description: "Area konservasi kecil dengan jalur interpretasi lingkungan.",
    ecoValue: "Kawasan konservasi untuk pelestarian flora dan fauna lokal.",
    activities: ["Tree planting", "Edukasi flora lokal", "Bird watching"],
    image: "/images/hutan-konservasi.jpg",
    eco: true,
  },
  {
    id: "kolam-edukasi-perikanan",
    name: "Kolam Edukasi Perikanan Berkelanjutan",
    type: "Edukasi Lingkungan",
    subtitle: "Bioflok System",
    description: "Kolam budidaya ikan dengan sistem bioflok ramah lingkungan.",
    ecoValue: "Sistem bioflok ramah lingkungan untuk budidaya ikan.",
    activities: ["Edukasi budidaya ikan", "Tangkap ikan & masak bersama"],
    image: "/images/kolam-edukasi.jpg",
    eco: true,
  },

  {
    id: "desa-adat-manud",
    name: "Desa Adat Manud",
    type: "Wisata Budaya",
    subtitle: "Warisan Budaya",
    description: "Area rumah tradisional dan balai budaya desa.",
    ecoValue: "Pelestarian budaya dan arsitektur tradisional.",
    activities: [
      "Workshop kerajinan bambu",
      "Belajar tarian tradisional",
      "Cerita sejarah desa",
    ],
    image: "/images/desa-adat.jpg",
    // image: "/packages/sunrise-eco.jpg",
    eco: false,
  },
];

export const packages = [
  {
    id: "sunrise-eco-escape",
    title: "Sunrise Eco Escape",
    duration: "1 Hari (05.00 \u2013 15.00)",
    price: 275000,
    eco: true,
    itinerary: [
      "05.00 \u2013 Sunrise trekking di Bukit Panorama Lestari",
      "07.30 \u2013 Sarapan lokal di Kedai Kopi Lembah Hijau",
      "09.00 \u2013 Edukasi sawah di Kampung Sawah Organik Mandiri",
      "11.30 \u2013 Makan siang organik",
      "13.00 \u2013 Workshop singkat eco-living",
      "15.00 \u2013 Selesai",
    ],
    includes: [
      "Guide local",
      "Sarapan & makan siang",
      "Tiket masuk lokasi",
      "Donasi konservasi",
    ],
    image: "/packages/sunrise-eco.jpg",
  },
  {
    id: "adventure-sehari",
    title: "Adventure Sehari di Manud",
    duration: "1 Hari",
    price: 325000,
    eco: true,
    itinerary: [
      "07.00 \u2013 Sarapan pagi",
      "08.00 \u2013 Trekking ke Air Terjun Tirta Manud",
      "10.00 \u2013 River tubing di Sungai Lestari",
      "12.30 \u2013 Makan siang",
      "14.00 \u2013 Coffee tasting lokal",
      "16.00 \u2013 Selesai",
    ],
    includes: [
      "Guide local",
      "Sarapan & makan siang",
      "Tiket masuk lokasi",
      "Donasi konservasi",
    ],
    image: "/packages/day-adventure.jpg",
  },
  {
    id: "eco-living-experience",
    title: "Eco Living Experience",
    duration: "2 Hari 1 Malam",
    price: 675000,
    eco: true,
    itinerary: [
      "07.00 \u2013 Sarapan pagi & briefing singkat",
      "08.00 \u2013 Trekking Bukit Panorama (sunrise view point & foto spot)",
      "10.00 \u2013 Istirahat ringan & air mineral/snack lokal",
      "10.30 \u2013 Trekking lanjutan menuju Air Terjun Tirta Manud",
      "12.00 \u2013 Waktu bebas di air terjun",
      "12.30 \u2013 Makan siang",
      "14.00 \u2013 Workshop kerajinan di Desa Adat",
      "16.00 \u2013 Jelajah singkat Desa Adat & sesi cerita budaya",
      "17.30 \u2013 Kembali ke homestay/area kumpul, istirahat & persiapan malam",
      "18.30 \u2013 Makan malam",
      "19.30 \u2013 Pertunjukan budaya malam (tari tradisional & musik lokal) + interaksi dengan warga",
      "21.00 \u2013 Selesai & istirahat",
    ],
    itinerary2: [
      "07.00 \u2013 Sarapan pagi",
      "08.00 \u2013 Aktivitas di Kampung Sawah Organik (tur sawah, pengenalan tanam/panen)",
      "10.00 \u2013 Praktik singkat: menanam/merawat tanaman (tergantung musim) + edukasi pupuk/kompos",
      "11.30 \u2013 Makan siang (hasil kebun/menu sehat)",
      "13.00 \u2013 Edukasi perikanan bioflok (konsep, proses, & demo pemberian pakan/quality check)",
      "14.30 \u2013 Sesi tanya jawab & foto bersama",
      "15.00 \u2013 Penutupan (review kegiatan, pembagian sertifikat/oleh-oleh) & check-out",
    ],
    includes: [
      "Guide local",
      "Sarapan, makan siang, & makan malam",
      "Tiket masuk lokasi",
      "Donasi konservasi",
    ],
    image: "/packages/eco-living.jpg",
  },
  {
    id: "family-green-getaway",
    title: "Family Green Getaway",
    duration: "2 Hari 1 Malam",
    price: 725000,
    eco: true,
    itinerary: [
      "07.00 \u2013 Sarapan pagi & briefing singkat (aturan kunjungan desa adat)",
      "08.00 \u2013 Tur Desa Adat (sejarah, tata ruang, rumah adat, area sakral & etika berkunjung)",
      "09.30 \u2013 Sesi cerita warga/tokoh adat (nilai budaya & tradisi lokal)",
      "10.30 \u2013 Workshop bambu (pengenalan jenis bambu, alat, teknik dasar)",
      "11.30 \u2013 Praktik membuat kerajinan bambu (souvenir/anyaman sederhana) + pendampingan",
      "12.30 \u2013 Makan siang",
      "14.00 \u2013 Kuliner tradisional: demo masak (bumbu lokal & cara olah) + tasting",
      "15.30 \u2013 Waktu bebas: belanja UMKM/produk lokal & foto spot desa",
      "16.30 \u2013 Istirahat & persiapan malam",
      "18.00 \u2013 Makan malam (menu tradisional desa)",
      "19.30 \u2013 Api unggun malam (games ringan, cerita rakyat, musik akustik lokal)",
      "21.00 \u2013 Selesai & istirahat",
    ],
    itinerary2: [
      "07.00 \u2013 Sarapan pagi",
      "08.00 \u2013 Kolam Edukasi Perikanan (pengenalan budidaya, pakan, kualitas air)",
      "09.30 \u2013 Demo aktivitas kolam (cek pH/DO sederhana, pemberian pakan, panen contoh)",
      "10.30 \u2013 Petik sayur organik (tur kebun, edukasi kompos & pestisida nabati)",
      "11.30 \u2013 Persiapan memasak bersama (cuci & olah hasil panen)",
      "12.30 \u2013 Makan siang keluarga (hidangan rumahan dari hasil kebun) + ngobrol santai warga",
      "13.30 \u2013 Penutupan (foto bersama, feedback singkat, pembagian oleh-oleh) & check-out",
    ],
    includes: [
      "Guide local",
      "Sarapan, makan siang, & makan malam",
      "Tiket masuk lokasi",
      "Donasi konservasi",
    ],
    image: "/packages/family-green.jpg",
  },
  {
    id: "sustainable-village-immersion",
    title: "Sustainable Village Immersion",
    duration: "3 Hari 2 Malam",
    price: 1250000,
    eco: true,
    itinerary: [
      "04.30 \u2013 Bangun & persiapan trekking (air minum, jaket, senter opsional)",
      "05.00 \u2013 Briefing rute + pemanasan ringan",
      "05.15 \u2013 Trekking Sunrise menuju spot Bukit Panorama",
      "06.00 \u2013 Tiba di sunrise point: menikmati sunrise + foto bersama",
      "07.00 \u2013 Trekking turun & kembali ke titik kumpul",
      "08.00 \u2013 Sarapan pagi",
      "09.00 \u2013 Perjalanan menuju Air Terjun",
      "09.30 \u2013 Trekking ringan ke Air Terjun",
      "10.00 \u2013 Tiba di Air Terjun: waktu bebas (foto/berenang opsional) + snack",
      "11.30 \u2013 Kembali ke titik kumpul & ganti baju",
      "12.30 \u2013 Makan siang",
      "14.00 \u2013 Coffee session: coffee tasting lokal + cerita proses (kebun–roasting–seduh)",
      "15.30 \u2013 Demo seduh manual (V60/tubruk) + mini workshop aroma & rasa",
      "16.30 \u2013 Istirahat & free time",
      "18.00 \u2013 Makan malam",
      "19.30 \u2013 Cultural night: pertunjukan budaya (tari/musik lokal) + interaksi warga",
      "21.00 \u2013 Selesai & istirahat",
    ],
    itinerary2: [
      "06.30 \u2013 Sarapan pagi",
      "07.30 \u2013 Tur Sawah Organik (pengenalan sistem tanam, irigasi, kompos)",
      "09.00 \u2013 Aktivitas sawah: praktik singkat tanam/panen (sesuai musim) + foto",
      "10.30 \u2013 Istirahat & minuman herbal lokal",
      "11.30 \u2013 Makan siang",
      "13.00 \u2013 Tree planting di Hutan Konservasi: briefing edukasi konservasi & safety",
      "13.30 \u2013 Penanaman pohon (jenis lokal) + penandaan nama/komitmen adopsi pohon",
      "15.00 \u2013 River tubing: briefing keselamatan, pembagian helm/pelampung",
      "15.30 \u2013 Start tubing (alur sungai, spot arus ringan–sedang) + dokumentasi",
      "16.45 \u2013 Finish tubing: bilas & ganti baju",
      "18.00 \u2013 Makan malam",
      "19.30 \u2013 Sharing session santai / api unggun opsional",
      "21.00 \u2013 Istirahat",
    ],
    itinerary3: [
      "07.00 \u2013 Sarapan pagi",
      "08.00 \u2013 Edukasi perikanan (bioflok/kolam budidaya): konsep, pakan, kualitas air",
      "09.30 \u2013 Demo lapangan: cek kualitas air sederhana + feeding/harvest sample",
      "10.30 \u2013 UMKM tour: kunjungan pelaku usaha lokal (kerajinan/olah pangan/kopi) + demo singkat",
      "12.00 \u2013 Makan siang",
      "13.30 \u2013 Penutupan (foto bersama, feedback, belanja produk lokal opsional) & check-out",
    ],
    includes: [
      "Guide local",
      "Sarapan, makan siang & makan malam",
      "Tiket masuk lokasi",
      "Donasi konservasi",
    ],
    image: "/packages/sustainable-village.jpg",
  },
  {
    id: "corporate-eco-retreat",
    title: "Corporate Eco Retreat",
    duration: "3 Hari 2 Malam",
    price: 1450000,
    eco: true,
    itinerary: [
      "07.00 \u2013 Kedatangan & welcome drink",
      "07.30 \u2013 Briefing itinerary & safety rules",
      "08.00 \u2013 Team building games ",
      "09.30 \u2013 Team challenge",
      "10.30 \u2013 Coffee session: coffee tasting lokal & sharing cerita kopi desa",
      "11.30 \u2013 Break & free time",
      "12.00 \u2013 Makan siang",
      "13.30 \u2013 Workshop sustainability",
      "15.00 \u2013 Praktik mini: pemilahan sampah/kompos/eco-craft sederhana",
      "16.00 \u2013 Diskusi refleksi: komitmen aksi kecil per tim (takeaway plan)",
      "17.30 \u2013 Istirahat & persiapan malam",
      "18.30 \u2013 Dinner budaya",
      "19.30 \u2013 Mini cultural night: musik/tari tradisional + interaksi warga",
      "21.00 \u2013 Selesai & istirahat",
    ],
    itinerary2: [
      "06.30 \u2013 Sarapan pagi",
      "07.30 \u2013 Briefing trekking (rute, pemanasan, perlengkapan)",
      "08.00 \u2013 Trekking menuju Air Terjun (stop foto & interpretasi alam)",
      "10.00 \u2013 Tiba di Air Terjun: istirahat, foto, waktu bebas (berenang opsional)",
      "11.30 \u2013 Kembali ke titik kumpul",
      "12.00 \u2013 Makan siang",
      "13.30 \u2013 Tree planting (edukasi jenis pohon, teknik tanam, penandaan nama)",
      "15.00 \u2013 River tubing (briefing safety, pembagian perlengkapan, start tubing)",
      "16.30 \u2013 Selesai tubing + bilas & ganti baju",
      "18.00 \u2013 Makan malam",
      "19.30 \u2013 Free time / sharing session santai",
      "21.00 \u2013 Istirahat",
    ],
    itinerary3: [
      "07.00 \u2013 Sarapan pagi",
      "08.00 \u2013 Edukasi perikanan (bioflok/kolam budidaya): konsep, pakan, kualitas air",
      "09.30 \u2013 Demo lapangan: cek air sederhana + feeding/harvest sample",
      "10.30 \u2013 UMKM tour (kunjungan pengrajin/produk olahan lokal) + demo produksi singkat",
      "12.00 \u2013 Makan siang",
      "13.30 \u2013 Local product shopping (pasar/gerai desa: kopi, madu, kerajinan, snack)",
      "15.00 \u2013 Penutupan (foto bersama, feedback, pembagian oleh-oleh/sertifikat) & check-out",
    ],
    includes: [
      "Guide local",
      "Sarapan, makan siang & makan malam",
      "Tiket masuk lokasi",
      "Donasi konservasi",
    ],
    image: "/packages/corporate-eco.jpg",
  },
];

export function formatRupiah(amount: number) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}
